### ISSUE TITLE
Update README.m2 to tell Fedora 20, RHEL 7, and CentOS 7 users not to use this container

### ISSUE THREAD

**Issue by docbill** [jpetazzo/nsenter#38]
You probably want to update your README.m2 file to tell users to check if they already have nsentry before using this.

There are several problems.   First off Fedora already includes nsentry by default.   It is part of the linux-utils package.  I was told the same is true for RHEL 7, and CentOS 7, but I haven't verified that. The same is probably true of many other distributions, so long as you are using the most recent versions.

The next problem is Fedora, RHEL 7, and CentOS 7 use SELinux settings so you can only mount folder with a special SELinux tag set via chattr as volumes.   As such your container won't work for mounting / as a volume.   Certainly the users could do a chattr on / to override this, but if they do so they are completely overriding a critical part of the security settings to overwrite something they already have installed.

Yet another problem is with your docker-enter script.   Quite frankly it doesn't work.   Well not everywhere.   You see it assumes flags on the env command that are not part of the POSIX standard.   So if for example I try using it on a busybox system or any other OS not using the GNU variant of env, it won't work.    I have an extremely simplified version of the script I use in my Fedora 20 system:
# !/bin/bash

p=$(docker inspect --format '{{.State.Pid}}' "$1")
shift
nsenter --target $p --mount --uts --ipc --net --pid -- "$@"

I'm not sure what probably you were trying to solve with your env command, but admittedly this variation does not solve that problem.   For Fedora 20, RHEL 7, CentOS, ... I just copy the script as docker-enter in my /usr/local/bin folder and I am good to go.

This version does however work on all the docker images I use.   One can also write this as an alias, but since normally it gets called with an sudo in front, it is more restrictive to use as an alias than as a script.

Bill

**Comment by jpetazzo** [comment]
I added a big disclaimer in the README to indicate that modern distros ship with nsenter, and that this is kept around just for historical purposes. Thanks for the feedback and the interest back then!
