### ISSUE TITLE
nsenter: cannot open /proc/<PID>/ns/ipc: Permission denied

### ISSUE THREAD

**Issue by denispeplin** [jpetazzo/nsenter#44]
I've seen message that I can handle docker without root permissions by adding myself to `docker` group: http://askubuntu.com/a/477554/115769.

It works, I really can get container ID and PID, but I can't use nsenter, error in subject:

`nsenter: cannot open /proc/<PID>/ns/ipc: Permission denied`

**Comment by dbajal** [comment]
I subscribe.
OpenSuse 13.1, nsenter 2.25.1, my groups:
```bash
$ groups 
users docker vboxusers
```
Making
```bash
$ nsenter --target $PID --mount --uts --ipc --net --pid
```
And get
> nsenter: cannot open /proc/7331/ns/ipc: Permission denied

That seem logical - 
```bash
(root) $ ls -la /proc/7331/ns/ipc
lrwxrwxrwx 1 root root 0 Apr  3 14:23 /proc/7331/ns/ipc -> ipc:[4026532897]
```

**Comment by jpetazzo** [comment]
Which version of Docker are you using? (`docker version`)

If it's recent enough, you can use `docker exec`.

Which version of the kernel are you using? (`uname -r`)

**Comment by dbajal** [comment]
```bash
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef
$ uname -r
3.16.7-7-desktop
```
Yeah, I've already thought of using `exec`, thank you. But I also thought nsenter should still be alive -)

**Comment by jpetazzo** [comment]
Are you using AppArmor or SELinux? Does anything particular show up in `dmesg` after trying to run `nsenter`?

**Comment by machzqcq** [comment]
Is this issue resolved by any chance. Without prepending "sudo", I am unable to nsenter (docker exec works fine though). I am using ubuntu 14.04 LTS and rest of the details are below

```
pmacharl@continuousautomation:~$ docker ps
CONTAINER ID        IMAGE                  COMMAND             CREATED             STATUS              PORTS               NAMES
3f742bab06d5        evarga/jenkins-slave   "/bin/bash"         5 minutes ago       Up 5 minutes        22/tcp              furious_saha
pmacharl@continuousautomation:~$ uname -r
4.1.5-x86_64-linode61
pmacharl@continuousautomation:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64
pmacharl@continuousautomation:~$ nsenter -m -u -n -p -i -t 6896 /bin/bash
nsenter: cannot open /proc/6896/ns/ipc: Permission denied
pmacharl@continuousautomation:~$ sudo nsenter -m -u -n -p -i -t 6896 /bin/bash
root@3f742bab06d5:/#

```

**Comment by jpetazzo** [comment]
Oh, sorry, I hadn't read this correctly. You _need_ permissions to use `nsenter`; in that case, it is likely that your UID doesn't match the UID of process 6896.
