### ISSUE TITLE
Cannot enter docker container anymore

### ISSUE THREAD

**Issue by bbinet** [jpetazzo/nsenter#45]
While docker-enter still works in most cases, I'm now unable to enter the following specific container:
https://registry.hub.docker.com/u/bbinet/salt-master/dockerfile/
I get the following error:
```
$ docker-enter salt-master
env: --config: No such file or directory
```

I think this problem has been introduced by #43, because docker-enter now tries to load the environment variable (which is great) but fail in my case because the `EXEC_CMD` environment is not escaped with double quotes.

See by yourself:
```
$ sudo cat /proc/$(docker inspect --format "{{.State.Pid}}" salt-master)/environ | xargs -n 1 -0
HOSTNAME=salt-master
EXEC_CMD=/usr/bin/salt-master --config /config --log-level debug
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
SHLVL=0
HOME=/root
BEFORE_EXEC_SCRIPT=/config/before-exec.sh
SALT_MASTER_CONFIG=/config/master
```

Maybe we can escape env variables with double quotes when parsing env variables with xargs:
https://github.com/jpetazzo/nsenter/blob/master/docker-enter#L31

**Comment by kurthuwig** [comment]
I've got it working with spaces using this:

    i=0
    unset ENV
    while IFS= read -r -d '' line; do
        ((i++))
        ENV[$i]="$line"
    done < /proc/$PID/environ

and

        $LAZY_SUDO "$NSENTER" $OPTS env -i - "${ENV[@]}" su -m root

The only remaining problem is, that you cannot use `sudo` to cat the environment variables as you the array is not transferred. But every other approach uses the "replace 0 with another character" approach and parses the output. This would trask the "another character" like like breaks.

**Comment by InAnimaTe** [comment]
This still seems to be a problem, see my [comment](https://github.com/jpetazzo/nsenter/pull/52#issuecomment-72889442) when trying to pass in my ssl keys and certs via variables.

**Comment by DanTheColoradan** [comment]
Same here with a [minecraft docker image](https://registry.hub.docker.com/u/itzg/minecraft-server/).

```{.sh}
env: -Xms1024M: No such file or directory
```

**Comment by ajdlinux** [comment]
See issue #62 and PR #64 - it's along the lines of @kurthuwig's patch above, but also uses sudo.
