### ISSUE TITLE
env: ... : No such file or directory

### ISSUE THREAD

**Issue by pierreozoux** [jpetazzo/nsenter#57]
It doesn't support env variables with spaces in it, and without quotes around.
I'm investigating to find a workaround.

**Comment by jpetazzo** [comment]
Maybe I'm missing something here, but it looks normal to me that variables without spaces should be quoted :-)

Can you give an example?

I will close the ticket for now but if you bring more details I'll of course re-open it.

Thank you!

**Comment by pierreozoux** [comment]
I have an env file containing:
```
...
APPLICATION=known
DOCKER_ARGUMENTS=--link mysql-example.org:db       -v /data/domains/example.org/known/data:/app/Uploads       -v /data/domains/example.org/known/.htaccess:/app/.htaccess       --env-file /data/domains/example.org/known/.env
...
```

And then it used by my unit file:
```
...
EnvironmentFile=/data/domains/%i/.env
ExecStart=/bin/bash -euxc ' \
  /opt/bin/systemd-docker --env run \
    --rm \
    --name %i \
    ${DOCKER_ARGUMENTS} \
    pierreozoux/${APPLICATION}'
...
```

Maybe, I'm doing this wrong, but it works. Then, it's just I'm not able to nsenter it. So I'm wondering how systemd manages to load this variable and nsenter not.
I actually really would like to solve the issue. But I didn't take the time... I'd prefer that we let it open. I'll look into it.
