### ISSUE TITLE
/target/docker-enter dangling symlink error

### ISSUE THREAD

**Issue by phpguru** [jpetazzo/nsenter#59]
Not sure why this is giving me grief today. 

    $ docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter
    Installing nsenter to /target
    Installing docker-enter to /target
    cp: not writing through dangling symlink '/target/docker-enter'

Version info:

    $ docker images
    jpetazzo/nsenter    latest              6ed3da1d7fa6        12 weeks ago        367.7 MB

**Comment by phpguru** [comment]
Removing the image and doing docker run again, forcing a download, seemed to fix it.

**Comment by jpetazzo** [comment]
OK, closing the issue then. Feel free to add more details if it happens again, and we'll reopen and investigate!

Thanks.
