### ISSUE TITLE
Warning when user trying to enter a stopped container

### ISSUE THREAD

**Issue by nqbao** [jpetazzo/nsenter#60]
It's obvious that we can't enter a stopped container and docker inspect will return pid as 0. It would be nice to have a friendly warning instead of display the error like below.

```
cat: /proc/0/environ: No such file or directory
nsenter: neither filename nor target pid supplied for ns/ipc
```

**Comment by jpetazzo** [comment]
Absolutely! I'm swamped right now, so I can't really work on this, but if you (or someone else) wants to provide a patch, I will be very grateful and happy to merge it.
