### ISSUE TITLE
Environment variables with spaces mess up docker-enter

### ISSUE THREAD

**Issue by michielbdejong** [jpetazzo/nsenter#62]
You can pass an environment variable with spaces into a container by using quotes, and bash can deal with that correctly inside the container:

```
michiel@laptop:~$ docker run -it -e A="1 2 3" debian:jessie /bin/bash
root@11f0509b89b1:/# echo $A
1 2 3
root@11f0509b89b1:/# 
```

But now try to docker-enter it from a different terminal window. That will fail:

```
michiel@laptop:~$ docker-enter 11f0509b89b1
env: 2: No such file or directory
```

**Comment by pierreozoux** [comment]
Hehe, I already opened it here: https://github.com/jpetazzo/nsenter/issues/57

Here is the simplified problem to solve: http://stackoverflow.com/questions/29390624/environment-variable-with-spaces-in-a-string-how-to-use-them-from-proc-pid-en

**Comment by pierreozoux** [comment]
As a work around, in `docker-enter` script put this:

```
ENV=$($LAZY_SUDO cat /proc/$PID/environ | tr '\0' '\n' | grep = | grep -v my_variable_with_spaces)
```

**Comment by michielbdejong** [comment]
@pierreozoux cool! Can you make that a pull request on this repo?

**Comment by pierreozoux** [comment]
Well, this is a work around. I can't predict `my_variable_with_space` :)

**Comment by michielbdejong** [comment]
ah ok, got it.

**Comment by ajdlinux** [comment]
+1, I just ran into this and it's very frustrating. I'm trying to figure out a proper solution but my bash-fu isn't quite good enough.

**Comment by ajdlinux** [comment]
Pull request I just submitted should provide a generic solution for this.
