### ISSUE TITLE
docker-enter issue for ssh tunnelling 

### ISSUE THREAD

**Issue by bendenoz** [jpetazzo/nsenter#67]
I have been trying to setup a "*utiliy*" container to upload files to docker volumes through `rsync / scp`.
In the end it works fine with but I just wanted to share that `docker exec` cannot yet fully replace `nsenter` because it does not completey exit in some cases.

See docker/docker#13052 for more details

/B

**Comment by jpetazzo** [comment]
`docker enter` or `docker exec`?

**Comment by bendenoz** [comment]
sorry `docker exec` (just edited the original text)

**Comment by jpetazzo** [comment]
OK, thanks! That makes sense. I'll leave this ticket open as a reminder to add a little section to the README maybe...

**Comment by icy** [comment]
+1. 

I finally got a `rsync` transport to work with `nsenter`.

It's strange that `nsenter` works where `docker exec [-t] [-i]` stucks. Here's `Docker-1.8.3`.  Thanks a lot.

**Comment by jpetazzo** [comment]
Cleaning up some older issues :-)

For future reference: the trick is to use rsync's `--blocking-io` option when using `docker exec -i` as a transport.
