### ISSUE TITLE
nsenter: cannot open /proc/19594/ns/pid: No such file or directory

### ISSUE THREAD

**Issue by michaelcourcy** [jpetazzo/nsenter#68]
Hi 

When I run docker-enter 

    docker-enter web bash

I get this error message 
    nsenter: cannot open /proc/19594/ns/pid: No such file or directory

the /proc/1954/ns directory does exist but no pid file inside 

Docker info 

    Images: 76
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 82
    Execution Driver: native-0.2
    Kernel Version: 3.2.0-4-amd64
    Operating System: Debian GNU/Linux 7 (wheezy)
    CPUs: 4
    Total Memory: 7.715 GiB
    Name: jude
    ID: VFCC:KISS:CUH2:2HRX:ELSP:SSK4:MA6I:Z3KG:K7DP:UNDH:HBAM:MEMA
    WARNING: No memory limit support
    WARNING: No swap limit support

**Comment by jpetazzo** [comment]
Hi! Your kernel is too old; it doesn't support entering the `pid` namespace.

Also, Docker and containers aren't stable on that kernel; you should try to upgrade to 3.8 at least.
