### ISSUE TITLE
/var/lib/boot2docker/docker-enter: line 43: importenv: not found

### ISSUE THREAD

**Issue by voldemortensen** [jpetazzo/nsenter#69]
Using the provided docker-enter function, I'm using `docker-enter <container_name>`, which results in:
`/var/lib/boot2docker/docker-enter: line 43: importenv: not found`

Using `boot2docker ssh` I have checked /var/lib/boot2docker/ and importenv exists.
Running `which importenv` returns nothing and I can't run `importenv` on it's own, however, I can run it like so `./importenv`

$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): darwin/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ boot2docker version
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc

**Comment by chermed** [comment]
Try this in the docker terminal :
`docker pull jpetazzo/nsenter`
`docker run --rm -v /usr/local/bin:/target jpetazzo/nsenter`

Then :

`docker-enter <container_name>`

Maybe it works

**Comment by voldemortensen** [comment]
That does temporarily fix it. I'll mark this as closed since I know how to fix my issue, and #70 addresses the root of the problem.
