### ISSUE TITLE
Can make the command `nsenter` simpler?

### ISSUE THREAD

**Issue by SydOps** [jpetazzo/nsenter#74]
run `docker-enter` is easier. Can we run `nsenter` with same way? If the options are never changed.

change from: 

    PID=$(docker inspect --format {{.State.Pid}} <container_name_or_ID>)
    nsenter --target $PID --mount --uts --ipc --net --pid

to

    nsenter <container_name_or_ID>

**Comment by SydOps** [comment]
Currently I create a simple script to simplify the command:

    $ cat denter
    PID=$(docker inspect --format {{.State.Pid}} $1)
    sudo nsenter --target $PID --mount --uts --ipc --net --pid

**Comment by jpetazzo** [comment]
Ah, why not use `docker-enter` directly in that case?

**Comment by SydOps** [comment]
@jpetazzo 

I think you knew the difference between `nsenter` and `docker-enter`, right?

**Comment by SydOps** [comment]
Seems my request is not accepted, I close this ticket, because I have the work around already and it is good enough.

**Comment by jpetazzo** [comment]
Ah, sorry, I hadn't understood your request.

To clarify (and for other people who could have similar ideas): `nsenter` is a tool in the `util-linux` package. I don't think that its authors and maintainers want to extend it to directly support Docker because that would be a fairly complicated extension. I believe (but I can be wrong) that the idea is to keep it simple and build on top of it. `docker-enter` precisely builds on top of it to integrate with Docker.

**Comment by SydOps** [comment]
Sure, let me explain more. 

With nsenter, 
```
(1) $ PID=$(docker inspect --format {{.State.Pid}} 08a2a025e05f)
(2) $ sudo nsenter --target $PID --mount --uts --ipc --net --pid
(3) $ ls /var/log              < #start from here, I am in container, and type the linux command directly
(4) $ df -h 
```
So with my work-around script, I run: 
(1) $ denter 08a2a025e05f
(2) $ ls /var/log
(3) $ df -h 

But with docker-enter, I need type:
```
(1) $ docker-enter 08a2a025e05f ls /var/log
(2) $ docker-enter 08a2a025e05f df -h
```

So I prefer my way, and that's the reason I raise this ticket.

**Comment by SydOps** [comment]
maybe I raise a pull request to add new command `denter` directly. let me do it and please check if you accept this way or not.

**Comment by jpetazzo** [comment]
But it already works that way:

```
docker@default:~$ docker run -dti alpine sh
bc5f1d9b7d7e7b2ff50906d987333a35f5614e09c95c72ba51cc6fb5e1df6f19
docker@default:~$ docker-enter bc5f
/ # ls
bin      etc      lib      media    proc     run      sys      usr
dev      home     linuxrc  mnt      root     sbin     tmp      var
/ # ps faux
PID   USER     TIME   COMMAND
    1 root       0:00 sh
    8 root       0:00 ash
   10 root       0:00 ps faux
```

**Comment by SydOps** [comment]
thanks, I didn't know that. I am fine now.

**Comment by jpetazzo** [comment]
OK, cool!
