### ISSUE TITLE
nsenter not working with docker beta for OS X / Windows

### ISSUE THREAD

**Issue by dzwicker** [jpetazzo/nsenter#82]
Hi,

there is no documentation how to use nsenter with the new Beta for OSX nor Windows docker support. This would be very nice.

**Comment by jpetazzo** [comment]
Hi!

It shouldn't be necessary to use nsenter anymore (`docker exec` replaces it for most purposes). If you have a use-case where `docker exec` doesn't fit, let us know!

I'll close this issue, but feel free to reply if you think otherwise.

Thank you,
