### ISSUE TITLE
After run docker run ... nsenter can not found

### ISSUE THREAD

**Issue by struCoder** [jpetazzo/nsenter#84]
Hi, i meet this problem

```shell
➜  ~ docker run --rm -v /usr/local/bin/:/target jpetazzo/nsenter
Installing nsenter to /target
Installing docker-enter to /target
Installing importenv to /target
➜  ~ nsenter
zsh: command not found: nsenter
```

**Comment by moul** [comment]
Hey @struCoder, can you try to call the full binary path: `/usr/local/bin/nsenter` instead of `nsenter`, your `$PATH` is probably missing the `/usr/local/bin` directory

**Comment by struCoder** [comment]
@moul 
Thanks, but i'm sure that `/usr/local/bin` is in `$PATH`.
if do this `docker run --rm -v /tmp:/target jpetazzo/nsenter`, i can find `nsenter`, `docker-enter`, `importent` in /tmp. That is interesting :）

**Comment by jpetazzo** [comment]
Did you find what was the problem?
