### ISSUE TITLE
remove a volume from running container

### ISSUE THREAD

**Issue by fahimeh2010** [jpetazzo/nsenter#85]
Hello

First thank for your open source code.
I saw the link about [https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/](url), it is possible to remove a volume from running containers? and how?

Thanks a lot

**Comment by jpetazzo** [comment]
Hi,

You can unmount it if you `nsenter`, but I don't recommend it. Also, I'd recommend to go by the `docker-user` mailing list for such questions :)

Cheers,
