### ISSUE TITLE
docker-enter/nsenter - no such file or directory

### ISSUE THREAD

**Issue by SebaBoler** [jpetazzo/nsenter#86]
I log into container "docker exec it xxxx bash"  and used command
But only get msg no such file or directory. What i doing wrong ??

**Comment by jpetazzo** [comment]
I don't know! I would suggest that you ask on StackOverflow, or on the `docker-user` mailing list.

(Maybe `docker exec -it xxxxx sh`, but what do I know...)

Thank you!
