### ISSUE TITLE
SFTP support?

### ISSUE THREAD

**Issue by krstns** [jpetazzo/nsenter#90]
Hello

I love nsenter since i can create dockerized environments for my web users and every one of them has their own environment, however it does not allow me to use sftp.
Is there any way I could get this to work?

**Comment by jpetazzo** [comment]
Hi!

I don't understand how you are using `nsenter`; but the purpose of nsenter was to provide a functionality similar to `docker exec`. Now that `docker exec` is available (and has been for a few years), `nsenter` should only be necessary for some really special usecases (e.g. using `docker exec` but with partial namespaces and cgroups).

Sincerely,

**Comment by krstns** [comment]
hello @jpetazzo 

I am using `nsenter` inside the `authorized_keys` of my users, so when they log in they get directly into the container and they can't get out.
I wanted to allow them to use sftp with that, but it seems that's not possible. The only "workaround" i have found is to use a sftp docker image with all of the users created and their volumes attached there.
