### ISSUE TITLE
I can't get "echo $MYENV " in the container 

### ISSUE THREAD

**Issue by sober-wang** [jpetazzo/nsenter#96]
when I into the container, use commend "nsenter --target <PID>--mount --uts --ipc --net --pid"
I want get my ENV , example echo $MYENV ,it show none
```shell
[root@localhost /]# docker inspect <CONTAINER_ID> --format '{{ .Config.Env}}' 
[MYENV=hello]
[root@localhost /]#  nsenter --target $(docker inspect <CONTAINER_ID>  --format '{{ .State.Pid}}') --mount --uts --ipc --net --pid
[root@localhost /]# echo $MYENV

[root@localhost /]# 
```

**Comment by thaJeztah** [comment]
Curious; is there a reason for you to not use `docker exec` instead of this project?

**Comment by sober-wang** [comment]
> 
> 
> Curious; is there a reason for you to not use `docker exec` instead of this project?

Yeas, when I used `docker exec ` into my-container ,I can use `echo $MYENV` got my environment variable. But I uesed `nsenter ` into my-container , I can't got it.

**Comment by jpetazzo** [comment]
@sober-wang I would suggest to use `docker exec` then.

This repository (jpetazzo/nsenter) was created _before_ `docker exec` existed. But now that we have `docker exec` it shouldn't be necessary anymore.

Thank you!
